import streamlit as st

st.title("Информация о наборе данных:")
st.header("Тематика датасета:Датчик дыма")
st.header("Описание признаков:")
st.write("- UTC: Всемирное координированное время")
st.write("- Temperature[C]: Температура в цельсиях")
st.write("- Humidity[%]: Влажность в процентах")
st.write("- TVOC[ppb]: Качество воздуха")
st.write("- eCO2[ppm]: Углекислый газ")
st.write("- Raw H2: Водород")
st.write("- Raw Ethanol: Этанол")
st.write("- Pressure[hPa]: Давление в гПА")
st.write("- PM1.0: Частицы PM1.0 ")
st.write("- PM2.5: Частицы PM2.5 ")
st.write("- NC0.5: Частицы NC0.5 ")
st.write("- NC1.0: Частицы NC1.0 ")
st.write("- NC2.5: Частицы NC2.5 ")
st.write("- CNT: Частицы CNT ")
st.write("- Fire Alarm: Датчик огня ")
st.header(" Предобработка данных:")
st.write("Нужно предсказать сработает датчик дыма или нет ")
st.write("В датасете были пропущенные значения. Они были удалены")
st.write("Были удалены дубликаты")
st.write("Преобразован столбец Fire Alarm в бинарный вид ")
